export const FETCH_MY_REQUESTS_REQUEST = "SEARCHBAR/FETCH_MY_REQUESTS_REQUEST";
export const FETCH_MY_REQUESTS_SUCCESS = "SEARCHBAR/FETCH_MY_REQUESTS_SUCCESS";
export const FETCH_MY_REQUESTS_FAILURE = "SEARCHBAR/FETCH_MY_REQUESTS_FAILURE";
export const SET_SEARCHBAR_DATA = "SEARCHBAR/SET_SEARCHBAR_DATA";
