export const FETCH_TODOLIST_REQUEST = "SEARCHBAR/FETCH_TODOLIST_REQUEST";
export const FETCH_TODOLIST_SUCCESS = "SEARCHBAR/FETCH_TODOLIST_SUCCESS";
export const FETCH_TODOLIST_FAILURE = "SEARCHBAR/FETCH_TODOLIST_FAILURE";
export const SET_SEARCHBAR_DATA = "SEARCHBAR/SET_SEARCHBAR_DATA";
