export const FETCH_SUMMARY_REQUEST = "SEARCHBAR/FETCH_SUMMARY_REQUEST";
export const FETCH_SUMMARY_SUCCESS = "SEARCHBAR/FETCH_SUMMARY_SUCCESS";
export const FETCH_SUMMARY_FAILURE = "SEARCHBAR/FETCH_SUMMARY_FAILURE";
export const SET_SEARCHBAR_DATA = "SEARCHBAR/SET_SEARCHBAR_DATA";
